config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :earnings_predictions

  resources :companies

  resources :price_items

  resources :topic_copies

  resources :topics

  resources :plans

  resources :prediction_economies

  resources :accounts

  resources :articles

  resources :cards

  resources :charges

  resources :bank_accounts

  resources :prediction_games

  resources :games

  resources :teams

  resources :sports

  resources :predictions

  resources :topics

  devise_for :users
  devise_for :admins
  devise_for :predictors

  root :to => 'pages#home'

  get "javatest" => "javascripts#dynamicgames.js"

  get 'home' => 'pages#home'

  get 'gamedash' => "games#index"

  get 'companies_quicksearch', :to => 'companies#quicksearch'

  get 'companies_index' => 'companies#index'

  get 'price_items' => "price_items#index"

  get 'top-posts' => 'pages#top_posts', as: 'top_posts'

  get '/me/bookmarks' => 'pages#bookmarks', as: 'bookmarks'

  get '/article/ajax_team/:team', :to => 'articles#ajax_team'

  get '/article/ajax_league/:game', :to => 'articles#ajax_league'

  get '/article/ajax_indicator/:typeId', :to => 'articles#ajax_indicator'

  get '/article/recommend/:article_id', :to => 'articles#ajax_recommend'

  get '/article/bookmark/:article_id', :to => 'articles#ajax_bookmark'

  get '/predictor/follow/:following_id', :to => 'predictors#ajax_following'

  get 'user_dashboard' => "pages#user_index"

  get "about" => "pages#about"

  get "login" => "devise/sessions#new"

  get 'dashboard' => 'pages#dashboard'

  get 'get_started' => 'pages#signup_dual_details'

  get 'all_categories' => 'pages#prediction_type_full_index'

  get 'predictoradminindex' => 'predictors#index'

  get 'select_category' => 'articles#select_category'

  get 'topic_copy_dashboard' => 'topic_copies#index'

  get 'posts' => 'articles#index'

  get 'experts' => 'predictors#predictorindex', as: 'predictorindex'

  get '/find-experts/:expert_type' => 'pages#findexperts', as: 'findexperts'

  get 'sportdashboard' => 'sports#index'

  post 'cards_default' => 'cards#make_default'

  post 'subscribe_new_card' => 'subscriptions#create'

  post 'update_predictor_price' => 'predictors#update_predictor_price'

  post 'bank_account_default' => 'bank_accounts#make_default'

  get '/:predictor/premium/confirm' => 'predictors#subscribe_confirm', as: 'subscribe_confirm'

  get 'subscribe' => 'subscriptions#create'

  get 'go_premium' => 'pages#premium_landing'

  get '/plan/:plan/confirm' => 'plans#confirm', as: 'plan_confirm'

  get 'plan/:plan/purchase' => 'plans#purchase', as: 'plan_purchase'

  get 'plans' => 'plans#index'

  get 'balance' => 'predictors#predictorbalance'

  get 'buy_prediction_game' => 'prediction_games#buy'

  get 'subscribe_to_predictor' => 'predictors#subscribe'

  get 'follow_predictor' => 'predictors#follow'

  get 'predictorpayeeedit' => 'accounts#edit'
  get 'bank_account_new' => 'bank_accounts#new'

  get '/users/edit/payments' => 'cards#index', as: 'payments'

  get '/tags/:tag' => 'pages#tag_show', as: 'tag_show'

  get '/topic/:topic' => 'pages#topic_show', as: 'topic_show_page'

  get '/topic/:topic/top' => 'pages#topic_top_articles', as: 'topic_top_articles'

  get '/topic/:topic/latest' => 'pages#topic_latest_articles', as: 'topic_latest_articles'

  get '/events/sports/:league' => 'games#findgames', as: 'find_prediction_games'

  get 'sports/leagues/:league/games/:id' => 'games#show', as: 'gameshow'

  get 'sports/leagues/:league/games/:id/predictions' => 'pages#gamepredictionindex', as: 'gamepredictionindex'

  get '/:league/games/:id/posts' => 'pages#gamearticleindex', as: 'gamearticleindex'

  get 'sports/leagues/:league/teams/:team' => 'teams#show', as: 'teamshow'

  get 'sports/leagues/:league/teams/:team/games' => 'teams#show_games', as: 'teamshowgames'

  get 'sports/leagues/:league/teams/:team/experts' => 'teams#expertindex', as: 'teamindexexperts'

  get '/:league/teams/:team/games' => 'teams#teamgameindex', as: 'teamgameindex'

  get 'sports/leagues/:league/teams' => 'sports#teamindex', as: 'sportsteamindex'

  get 'sports/leagues/:league/experts' => 'sports#expertindex', as: 'sportsexpertindex'

  get '/events/sports/:league/predictions/:game_id' => 'prediction_games#findpredictiongames', as: 'find_sports_predictions'
  
  get '/predictors/sports/:league' => 'predictors#findsportspredictors', as: 'find_sports_predictors'

  get '/:username/predictions' => 'predictors#predictionindex', as: 'predictorindexpredictions'

  get '/:username/rating' => 'predictors#rating', as: 'predictor_rating'

  get '/:username/predictions/:category' => 'predictors#predictionindex', as: 'predictorindexpredictionscategory'

  get '/:username/' => 'predictors#predictordashboard', as: 'predictordashboard'

  get '/:username/posts' => 'predictors#articleindex', as: 'predictorindexarticlessall'

  get '/posts/new/' => 'articles#new', as: 'new_post'

  get '/:username/posts/:id' => 'articles#show', as: 'predictorarticleshow'

  get '/:username/:category/leagues/:league' => 'predictors#predictionindex', as: 'predictorindexpredictionsleague'

  get '/buyprediction/sports/:id' => 'prediction_games#buy', as: 'buypredictiongame'

  get '/:username/:type/new/sports/' => 'games#sportsgamesselect', as: 'sportsgamesselect'

  get '/:username/predictions/sports/:id' => 'prediction_games#show', as: 'predictiongamesshow'

  get 'prediction/sports/new/:id' => 'prediction_games#new', as: 'newpredictiongame'

  
  get '/:username/subscribers' => 'predictors#subscriberindex', as: 'predictorsubscriberindex'

  get ':league/posts/all/index' => 'pages#leaguearticleindex', as: 'leaguearticleindex'

  get 'sports/leagues/:league/predictions' => 'pages#leaguepredictionindex', as: 'leaguepredictionindex'

  get ':league/games' => 'pages#leaguegameindex', as: 'leaguegameindex'

  get 'sports/leagues/:league' => 'pages#leaguehome', as: 'leaguehome'

  get 'sports/leagues/:league/experts' => 'pages#league_predictors', as: 'leaguepredictors'

  get 'sports/leagues/:league/games' => 'pages#league_games', as: 'leaguegames'

  get 'editor' => 'sports#new'

  get '/posts/all/:type' => 'articles#index', as: 'articledashboard'

  get 'economics/:category' => 'prediction_economies#index', as: 'prediction_economies_index'

  get 'watchlist' =>'pages#mywatchlist'

  get 'sports-watchlist' => 'pages#sportswatchlist'
  get 'finance-watchlist' => 'pages#financewatchlist'
  get 'politics-watchlist' => 'pages#politicswatchlist'
  get 'misc-watchlist' => 'pages#miscwatchlist'

  get '/find-predictions/:prediction_type' => 'pages#findpredictions', as: 'findpredictions'

  get 'findsportspredictions' => 'prediction_games#findpredictiongames'

  get 'predictor_signin' => 'predictors#session#new'

  get 'myclosedpredictions' => 'prediction_games#index_closed'

  get 'predictiontype' => 'predictions#typeselect'

  get 'predictorpricing' => 'pages#predictorpricing'

  get 'sportsprediction' => 'predictions#newsportsprediction'

  get 'financeprediction' => 'predictions#newfinanceprediction'

  get 'miscprediction' => 'predictions#newmiscprediction'

  get 'admineditor' => 'admin#editor'

  get 'sportedit' => 'sports#index'

  get 'teamedit' => 'teams#index'

  get 'add_teams' => 'teams#new'

  get 'gamescore' => 'games#score'

  get 'sportpredictiontype' => 'pages#selectsportsprediction'

  get 'gameprediction' => 'prediction_games#index' #need

  get 'gameselect' => 'games#gameselect'

 

  get '/buyprediction/sports/:id' => 'prediction_games#show', as: 'showpredictiongame'

  post '/accounts/update' => 'accounts#update', as: 'accounts_update'
  

end

app/models/sport.rb
class Sport < ActiveRecord::Base

	has_many :teams
	has_many :games

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
						:s3_protocol => :https

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	
    has_attached_file :banner_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
						:s3_protocol => :https

	validates_attachment_content_type :banner_image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def recent_prediction_games

		myPurchases = Purchase.all.where(:user_id => self.id)

		sport_prediction_games = PredictionGame.all.where(:league=>self.subcat)
		
    	predictions = Array.new 

    	sport_prediction_games.each do |sport_prediction_game|

    		predictor = Predictor.find(sport_prediction_game.predictor_id)

            game = Game.find(sport_prediction_game.game_id)

          	hash = {:prediction=>sport_prediction_game, :predictor=> predictor, :game => game}

          	predictions << hash

        end
    
    	return predictions.sort_by {|k| k[:prediction].created_at}.reverse

	end

	def all_predictors

        predictors = Array.new

        league = self

        league_predictors = Predictor.all

        league_predictors.each do |league_predictor|

            if league_predictor.prediction_games.all.where("league = :league", {league: league.subcat}).count > 0

                predictors << league_predictor

            end
          
        end

        return predictors

    end

	def all_games

        games = Array.new

        league = self

        team_games = Game.all.where("(league = :league)", {league: league.subcat})

        team_games.each do |team_game|

            games << team_game
          
        end

        return games.sort_by {|k| k.event_time} 

    end

    def upcoming_games

        games = Array.new

        league = self

        team_games = Game.all.where("event_time > :time_now and (league = :league)", {league: league.subcat, time_now: Time.now})

        team_games.each do |team_game|

            games << team_game
          
        end

        return games.sort_by {|k| k.event_time} 

    end

end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  # GET /sports
  # GET /sports.json
  def index
    @sports = Sport.all
  end

  # GET /sports/1
  # GET /sports/1.json
  def show
  end

  # GET /sports/new
  def new
    @sport = Sport.new
  end

  # GET /sports/1/edit
  def edit
  end

  def teamindex
      
      @league = params[:league]

      @sport = Sport.find_by_subcat(@league)

      @teams = Team.all.where(:league => @league).sort_by {|k| k.name} 

  end

  def expertindex
      
      @league = params[:league]

      @experts = Sport.find_by_subcat(@league).all_predictors

      #@experts = Predictor.all.where(:league => @league).sort_by {|k| k.name} 
      #probably need a custom model

  end

  # POST /sports
  # POST /sports.json
  def create
    @sport = Sport.new(sport_params)

    respond_to do |format|
      if @sport.save
        format.html { redirect_to @sport, notice: 'Sport was successfully created.' }
        format.json { render :show, status: :created, location: @sport }
      else
        format.html { render :new }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sports/1
  # PATCH/PUT /sports/1.json
  def update
    respond_to do |format|
      if @sport.update(sport_params)
        format.html { redirect_to @sport, notice: 'Sport was successfully updated.' }
        format.json { render :show, status: :ok, location: @sport }
      else
        format.html { render :edit }
        format.json { render json: @sport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sports/1
  # DELETE /sports/1.json
  def destroy
    @sport.destroy
    respond_to do |format|
      format.html { redirect_to sports_url, notice: 'Sport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sport
      @sport = Sport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sport_params
      params.require(:sport).permit(:subcat, :image, :banner_image, :current_season)
      
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.erb
<%= form_for(@sport) do |f| %>
  <% if @sport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sport.errors.count, "error") %> prohibited this sport from being saved:</h2>

      <ul>
      <% @sport.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.label :subcat %><br>
    <%= f.text_field :subcat %>

    <%= f.label :current_season %><br>
    <%= f.text_field :current_season %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>

    <%= f.label :banner_image %>
    <%= f.file_field :banner_image, class: "form-control" %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/sports/_header_banner_image.html.erb
<div class = "header_image_banner_container">

  <div class = "header_image_banner_inner">
    <h1><%=@league%> Predictions</h1>
  </div>

  <%= image_tag @sport.banner_image.url, class: "header-img" %> 

</div>

app/views/sports/_leaguesummarymenu.html.erb
<ul class="subheader-menu-list">

  <li><b><%=@league%> Teams:</b></li>

  <% @teams.each do |team| %>

      <li><%= link_to team.name, teamshow_path(@league,team.id)%></li>

  <%end%>

</ul>

<!-- <table class ="game-show-table">

  <tr>
    <th>1</th>
    <th>2</th>
    <th>3</th>
  </tr>

  <tr>
    <th>a</th>
    <th>b</th>
    <th>c</th>
  </tr>

    <tr>
      <td>z</td>
      <td>y</td>
      <td>x</td>
      <td>w</td>
    </tr>

    <tr>
      <td>a1</td>
      <td>b2</td>
      <td>c3</td>
      <td>d4</td>
    </tr>
</table> -->

app/views/sports/_sportshowcover.html.erb
<div class = "cover-wrap">

	<div class="cover-container">

		<ul class="horizontal-cover">

			<li class="subheader-league">
				<%= image_tag Sport.find_by_subcat(@league).image.url(:medium, :width => 30, :height => 30), class: "sport-image-small"%><%= link_to @league, leaguehome_path(@league), class: "subheader-league"  %>
			</li>

			<li id="home"><%= link_to "Home", leaguehome_path(@league), {:class=>"subheader"} %></li>

			<li id="games"><%= link_to "Games", leaguegames_path(@league), {:class=>"subheader"} %></li>

			<li id="teams"><%= link_to "Teams", sportsteamindex_path(@league), {:class=>"subheader"} %></li>

			<li id="experts"><%= link_to "Experts", sportsexpertindex_path(@league), {:class=>"subheader"} %></li>

		</ul>
    

  </div>

</div>

app/views/sports/edit.html.erb
<h1>Editing sport</h1>

<%= render 'form' %>

<%= link_to 'Show', @sport %> |
<%= link_to 'Back', sports_path %>

app/views/sports/expertindex.html.erb
<script>
    $(document).ready(function(){
      $("#experts").addClass("active");
    });
</script>

<%= render 'sports/sportshowcover' %>

<div class="content-panel-wrap">

	<div class="content-panel">

	  <div class="content-panel-container">
	    
	    <h1><%=@league%> Experts</h1>

	    <div class="large-table-container">

	    	<table class="game-schedule-table">

				<thead>
					<tr class="game-table-header">
						<th>EXPERT</th>
						<th style="text-align:center;"><%=@league%> PREDICTIONS</th>
						<th style="text-align:center;"><%=@league%> RATING</th>
					</tr>
				</thead>

				<tbody>
					
					<% @experts.each do |expert| %>
						
						<tr data-link="<%= predictordashboard_path(expert.username)%>" class="game-table-row">
							<td><%= image_tag expert.image.url(:medium), class: "predictor-image-tiny"%><%= expert.username %></td>
							<td style="text-align:center;"><%= expert.league_predictions(@league).count %></td>
							<td style="text-align:center;"><%=expert.sport_predictions_rating(@league)%></td>
						</tr>

					<%end%>

				</tbody>

			</table>

	    </div>

	  </div>

	</div>

</div>

app/views/sports/index.html.erb
<h1>Listing sports</h1>

<table>
  <thead>
    <tr>
      <th>Subcat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sports.each do |sport| %>
      <tr>
        <td><%= sport.subcat %></td>
        <td><%= link_to 'Show', sport %></td>
        <td><%= link_to 'Edit', edit_sport_path(sport) %></td>

        <td> <%= link_to 'Teams', sport %> <td>

        <td><%= link_to 'Destroy', sport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Team Dash', teams_path %>

<%= link_to 'Game Dash', games_path %>

<%= link_to 'New Sport', new_sport_path %>

app/views/sports/new.html.erb
<h1>New sport</h1>

<%= render 'form' %>

<%= link_to 'Back', sports_path %>

app/views/sports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subcat:</strong>
  <%= @sport.subcat %>
</p>

<%= image_tag @sport.image.url(:thumb) %>

<%= link_to 'Edit', edit_sport_path(@sport) %> |
<%= link_to 'Back', sports_path %>

app/views/sports/sportteamindex.html.erb
<script>
    $(document).ready(function(){
      $("#teams").addClass("active");
    });
</script>

<%= render 'sports/sportshowcover' %>

<div class="content-panel">

  <div class="content-panel-container">
    <h1><%=@league%> Teams</h1>

  </div>

</div>

app/views/sports/teamindex.html.erb
<script>
    $(document).ready(function(){
      $("#teams").addClass("active");
    });
</script>

<%= render 'sports/sportshowcover' %>

<div class="content-panel-wrap">

	<div class="content-panel">

	  <div class="content-panel-container">
	    <h1><%=@league%> Teams</h1>

	    <div class="large-table-container">

	    	<table class="game-schedule-table">
				<tbody>
					
					<% @teams.each do |team| %>
						
						<tr data-link="<%=teamshow_path(team.league, team.name)%>" class="game-table-row">
							<td style="text-align:center;"><%= image_tag team.image, class: "team-image-tiny"%> <%=team.full_name %> <%= team.sport_id%></td>
						</tr>

					<%end%>

				</tbody>

			</table>

	    </div>

	  </div>

	</div>

</div>