config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :earnings_predictions

  resources :companies

  resources :price_items

  resources :topic_copies

  resources :topics

  resources :plans

  resources :prediction_economies

  resources :accounts

  resources :articles

  resources :cards

  resources :charges

  resources :bank_accounts

  resources :prediction_games

  resources :games

  resources :teams

  resources :sports

  resources :predictions

  resources :topics

  devise_for :users
  devise_for :admins
  devise_for :predictors

  root :to => 'pages#home'

  get "javatest" => "javascripts#dynamicgames.js"

  get 'home' => 'pages#home'

  get 'gamedash' => "games#index"

  get 'companies_quicksearch', :to => 'companies#quicksearch'

  get 'companies_index' => 'companies#index'

  get 'price_items' => "price_items#index"

  get 'top-posts' => 'pages#top_posts', as: 'top_posts'

  get '/me/bookmarks' => 'pages#bookmarks', as: 'bookmarks'

  get '/article/ajax_team/:team', :to => 'articles#ajax_team'

  get '/article/ajax_league/:game', :to => 'articles#ajax_league'

  get '/article/ajax_indicator/:typeId', :to => 'articles#ajax_indicator'

  get '/article/recommend/:article_id', :to => 'articles#ajax_recommend'

  get '/article/bookmark/:article_id', :to => 'articles#ajax_bookmark'

  get '/predictor/follow/:following_id', :to => 'predictors#ajax_following'

  get 'user_dashboard' => "pages#user_index"

  get "about" => "pages#about"

  get "login" => "devise/sessions#new"

  get 'dashboard' => 'pages#dashboard'

  get 'get_started' => 'pages#signup_dual_details'

  get 'all_categories' => 'pages#prediction_type_full_index'

  get 'predictoradminindex' => 'predictors#index'

  get 'select_category' => 'articles#select_category'

  get 'topic_copy_dashboard' => 'topic_copies#index'

  get 'posts' => 'articles#index'

  get 'experts' => 'predictors#predictorindex', as: 'predictorindex'

  get '/find-experts/:expert_type' => 'pages#findexperts', as: 'findexperts'

  get 'sportdashboard' => 'sports#index'

  post 'cards_default' => 'cards#make_default'

  post 'subscribe_new_card' => 'subscriptions#create'

  post 'update_predictor_price' => 'predictors#update_predictor_price'

  post 'bank_account_default' => 'bank_accounts#make_default'

  get '/:predictor/premium/confirm' => 'predictors#subscribe_confirm', as: 'subscribe_confirm'

  get 'subscribe' => 'subscriptions#create'

  get 'go_premium' => 'pages#premium_landing'

  get '/plan/:plan/confirm' => 'plans#confirm', as: 'plan_confirm'

  get 'plan/:plan/purchase' => 'plans#purchase', as: 'plan_purchase'

  get 'plans' => 'plans#index'

  get 'balance' => 'predictors#predictorbalance'

  get 'buy_prediction_game' => 'prediction_games#buy'

  get 'subscribe_to_predictor' => 'predictors#subscribe'

  get 'follow_predictor' => 'predictors#follow'

  get 'predictorpayeeedit' => 'accounts#edit'
  get 'bank_account_new' => 'bank_accounts#new'

  get '/users/edit/payments' => 'cards#index', as: 'payments'

  get '/tags/:tag' => 'pages#tag_show', as: 'tag_show'

  get '/topic/:topic' => 'pages#topic_show', as: 'topic_show_page'

  get '/topic/:topic/top' => 'pages#topic_top_articles', as: 'topic_top_articles'

  get '/topic/:topic/latest' => 'pages#topic_latest_articles', as: 'topic_latest_articles'

  get '/events/sports/:league' => 'games#findgames', as: 'find_prediction_games'

  get 'sports/leagues/:league/games/:id' => 'games#show', as: 'gameshow'

  get 'sports/leagues/:league/games/:id/predictions' => 'pages#gamepredictionindex', as: 'gamepredictionindex'

  get '/:league/games/:id/posts' => 'pages#gamearticleindex', as: 'gamearticleindex'

  get 'sports/leagues/:league/teams/:team' => 'teams#show', as: 'teamshow'

  get 'sports/leagues/:league/teams/:team/games' => 'teams#show_games', as: 'teamshowgames'

  get 'sports/leagues/:league/teams/:team/experts' => 'teams#expertindex', as: 'teamindexexperts'

  get '/:league/teams/:team/games' => 'teams#teamgameindex', as: 'teamgameindex'

  get 'sports/leagues/:league/teams' => 'sports#teamindex', as: 'sportsteamindex'

  get 'sports/leagues/:league/experts' => 'sports#expertindex', as: 'sportsexpertindex'

  get '/events/sports/:league/predictions/:game_id' => 'prediction_games#findpredictiongames', as: 'find_sports_predictions'
  
  get '/predictors/sports/:league' => 'predictors#findsportspredictors', as: 'find_sports_predictors'

  get '/:username/predictions' => 'predictors#predictionindex', as: 'predictorindexpredictions'

  get '/:username/rating' => 'predictors#rating', as: 'predictor_rating'

  get '/:username/predictions/:category' => 'predictors#predictionindex', as: 'predictorindexpredictionscategory'

  get '/:username/' => 'predictors#predictordashboard', as: 'predictordashboard'

  get '/:username/posts' => 'predictors#articleindex', as: 'predictorindexarticlessall'

  get '/posts/new/' => 'articles#new', as: 'new_post'

  get '/:username/posts/:id' => 'articles#show', as: 'predictorarticleshow'

  get '/:username/:category/leagues/:league' => 'predictors#predictionindex', as: 'predictorindexpredictionsleague'

  get '/buyprediction/sports/:id' => 'prediction_games#buy', as: 'buypredictiongame'

  get '/:username/:type/new/sports/' => 'games#sportsgamesselect', as: 'sportsgamesselect'

  get '/:username/predictions/sports/:id' => 'prediction_games#show', as: 'predictiongamesshow'

  get 'prediction/sports/new/:id' => 'prediction_games#new', as: 'newpredictiongame'

  
  get '/:username/subscribers' => 'predictors#subscriberindex', as: 'predictorsubscriberindex'

  get ':league/posts/all/index' => 'pages#leaguearticleindex', as: 'leaguearticleindex'

  get 'sports/leagues/:league/predictions' => 'pages#leaguepredictionindex', as: 'leaguepredictionindex'

  get ':league/games' => 'pages#leaguegameindex', as: 'leaguegameindex'

  get 'sports/leagues/:league' => 'pages#leaguehome', as: 'leaguehome'

  get 'sports/leagues/:league/experts' => 'pages#league_predictors', as: 'leaguepredictors'

  get 'sports/leagues/:league/games' => 'pages#league_games', as: 'leaguegames'

  get 'editor' => 'sports#new'

  get '/posts/all/:type' => 'articles#index', as: 'articledashboard'

  get 'economics/:category' => 'prediction_economies#index', as: 'prediction_economies_index'

  get 'watchlist' =>'pages#mywatchlist'

  get 'sports-watchlist' => 'pages#sportswatchlist'
  get 'finance-watchlist' => 'pages#financewatchlist'
  get 'politics-watchlist' => 'pages#politicswatchlist'
  get 'misc-watchlist' => 'pages#miscwatchlist'

  get '/find-predictions/:prediction_type' => 'pages#findpredictions', as: 'findpredictions'

  get 'findsportspredictions' => 'prediction_games#findpredictiongames'

  get 'predictor_signin' => 'predictors#session#new'

  get 'myclosedpredictions' => 'prediction_games#index_closed'

  get 'predictiontype' => 'predictions#typeselect'

  get 'predictorpricing' => 'pages#predictorpricing'

  get 'sportsprediction' => 'predictions#newsportsprediction'

  get 'financeprediction' => 'predictions#newfinanceprediction'

  get 'miscprediction' => 'predictions#newmiscprediction'

  get 'admineditor' => 'admin#editor'

  get 'sportedit' => 'sports#index'

  get 'teamedit' => 'teams#index'

  get 'add_teams' => 'teams#new'

  get 'gamescore' => 'games#score'

  get 'sportpredictiontype' => 'pages#selectsportsprediction'

  get 'gameprediction' => 'prediction_games#index' #need

  get 'gameselect' => 'games#gameselect'

 

  get '/buyprediction/sports/:id' => 'prediction_games#show', as: 'showpredictiongame'

  post '/accounts/update' => 'accounts#update', as: 'accounts_update'
  

end

app/models/company.rb
class Company < ActiveRecord::Base



end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    # I will explain this part in a moment.
    if params[:term]
      @companies = Company.find(:all,:conditions => ['name LIKE ?', "#{params[:term]}%"])
    else
      @company = Company.all
    end

    respond_to do |format|  
      format.html # index.html.erb  
    # Here is where you can specify how to handle the request for "/company.json"
      format.json { render :json => @company.to_json }
      end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  def quicksearch

    @companies = Company.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @companies.map(&:name)

  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :ticker, :exchange, :sector, :sub_sector, :industry_group, :country, :next_filing_date, :datetime, :status, :ein)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ticker %><br>
    <%= f.text_field :ticker %>
  </div>
  <div class="field">
    <%= f.label :exchange %><br>
    <%= f.text_field :exchange %>
  </div>
  <div class="field">
    <%= f.label :sector %><br>
    <%= f.text_field :sector %>
  </div>
  <div class="field">
    <%= f.label :sub_sector %><br>
    <%= f.text_field :sub_sector %>
  </div>
  <div class="field">
    <%= f.label :industry_group %><br>
    <%= f.text_field :industry_group %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :next_filing_date %><br>
    <%= f.text_field :next_filing_date %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.text_field :datetime %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :ein %><br>
    <%= f.text_field :ein %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ticker</th>
      <th>Exchange</th>
      <th>Sector</th>
      <th>Sub sector</th>
      <th>Industry group</th>
      <th>Country</th>
      <th>Next filing date</th>
      <th>Datetime</th>
      <th>Status</th>
      <th>Ein</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.ticker %></td>
        <td><%= company.exchange %></td>
        <td><%= company.sector %></td>
        <td><%= company.sub_sector %></td>
        <td><%= company.industry_group %></td>
        <td><%= company.country %></td>
        <td><%= company.next_filing_date %></td>
        <td><%= company.datetime %></td>
        <td><%= company.status %></td>
        <td><%= company.ein %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/quicksearch.html.erb
views

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @company.ticker %>
</p>

<p>
  <strong>Exchange:</strong>
  <%= @company.exchange %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @company.sector %>
</p>

<p>
  <strong>Sub sector:</strong>
  <%= @company.sub_sector %>
</p>

<p>
  <strong>Industry group:</strong>
  <%= @company.industry_group %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<p>
  <strong>Next filing date:</strong>
  <%= @company.next_filing_date %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @company.datetime %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Ein:</strong>
  <%= @company.ein %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>