config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :earnings_predictions

  resources :companies

  resources :price_items

  resources :topic_copies

  resources :topics

  resources :plans

  resources :prediction_economies

  resources :accounts

  resources :articles

  resources :cards

  resources :charges

  resources :bank_accounts

  resources :prediction_games

  resources :games

  resources :teams

  resources :sports

  resources :predictions

  resources :topics

  devise_for :users
  devise_for :admins
  devise_for :predictors

  root :to => 'pages#home'

  get "javatest" => "javascripts#dynamicgames.js"

  get 'home' => 'pages#home'

  get 'gamedash' => "games#index"

  get 'companies_quicksearch', :to => 'companies#quicksearch'

  get 'companies_index' => 'companies#index'

  get 'price_items' => "price_items#index"

  get 'top-posts' => 'pages#top_posts', as: 'top_posts'

  get '/me/bookmarks' => 'pages#bookmarks', as: 'bookmarks'

  get '/article/ajax_team/:team', :to => 'articles#ajax_team'

  get '/article/ajax_league/:game', :to => 'articles#ajax_league'

  get '/article/ajax_indicator/:typeId', :to => 'articles#ajax_indicator'

  get '/article/recommend/:article_id', :to => 'articles#ajax_recommend'

  get '/article/bookmark/:article_id', :to => 'articles#ajax_bookmark'

  get '/predictor/follow/:following_id', :to => 'predictors#ajax_following'

  get 'user_dashboard' => "pages#user_index"

  get "about" => "pages#about"

  get "login" => "devise/sessions#new"

  get 'dashboard' => 'pages#dashboard'

  get 'get_started' => 'pages#signup_dual_details'

  get 'all_categories' => 'pages#prediction_type_full_index'

  get 'predictoradminindex' => 'predictors#index'

  get 'select_category' => 'articles#select_category'

  get 'topic_copy_dashboard' => 'topic_copies#index'

  get 'posts' => 'articles#index'

  get 'experts' => 'predictors#predictorindex', as: 'predictorindex'

  get '/find-experts/:expert_type' => 'pages#findexperts', as: 'findexperts'

  get 'sportdashboard' => 'sports#index'

  post 'cards_default' => 'cards#make_default'

  post 'subscribe_new_card' => 'subscriptions#create'

  post 'update_predictor_price' => 'predictors#update_predictor_price'

  post 'bank_account_default' => 'bank_accounts#make_default'

  get '/:predictor/premium/confirm' => 'predictors#subscribe_confirm', as: 'subscribe_confirm'

  get 'subscribe' => 'subscriptions#create'

  get 'go_premium' => 'pages#premium_landing'

  get '/plan/:plan/confirm' => 'plans#confirm', as: 'plan_confirm'

  get 'plan/:plan/purchase' => 'plans#purchase', as: 'plan_purchase'

  get 'plans' => 'plans#index'

  get 'balance' => 'predictors#predictorbalance'

  get 'buy_prediction_game' => 'prediction_games#buy'

  get 'subscribe_to_predictor' => 'predictors#subscribe'

  get 'follow_predictor' => 'predictors#follow'

  get 'predictorpayeeedit' => 'accounts#edit'
  get 'bank_account_new' => 'bank_accounts#new'

  get '/users/edit/payments' => 'cards#index', as: 'payments'

  get '/tags/:tag' => 'pages#tag_show', as: 'tag_show'

  get '/topic/:topic' => 'pages#topic_show', as: 'topic_show_page'

  get '/topic/:topic/top' => 'pages#topic_top_articles', as: 'topic_top_articles'

  get '/topic/:topic/latest' => 'pages#topic_latest_articles', as: 'topic_latest_articles'

  get '/events/sports/:league' => 'games#findgames', as: 'find_prediction_games'

  get 'sports/leagues/:league/games/:id' => 'games#show', as: 'gameshow'

  get 'sports/leagues/:league/games/:id/predictions' => 'pages#gamepredictionindex', as: 'gamepredictionindex'

  get '/:league/games/:id/posts' => 'pages#gamearticleindex', as: 'gamearticleindex'

  get 'sports/leagues/:league/teams/:team' => 'teams#show', as: 'teamshow'

  get 'sports/leagues/:league/teams/:team/games' => 'teams#show_games', as: 'teamshowgames'

  get 'sports/leagues/:league/teams/:team/experts' => 'teams#expertindex', as: 'teamindexexperts'

  get '/:league/teams/:team/games' => 'teams#teamgameindex', as: 'teamgameindex'

  get 'sports/leagues/:league/teams' => 'sports#teamindex', as: 'sportsteamindex'

  get 'sports/leagues/:league/experts' => 'sports#expertindex', as: 'sportsexpertindex'

  get '/events/sports/:league/predictions/:game_id' => 'prediction_games#findpredictiongames', as: 'find_sports_predictions'
  
  get '/predictors/sports/:league' => 'predictors#findsportspredictors', as: 'find_sports_predictors'

  get '/:username/predictions' => 'predictors#predictionindex', as: 'predictorindexpredictions'

  get '/:username/rating' => 'predictors#rating', as: 'predictor_rating'

  get '/:username/predictions/:category' => 'predictors#predictionindex', as: 'predictorindexpredictionscategory'

  get '/:username/' => 'predictors#predictordashboard', as: 'predictordashboard'

  get '/:username/posts' => 'predictors#articleindex', as: 'predictorindexarticlessall'

  get '/posts/new/' => 'articles#new', as: 'new_post'

  get '/:username/posts/:id' => 'articles#show', as: 'predictorarticleshow'

  get '/:username/:category/leagues/:league' => 'predictors#predictionindex', as: 'predictorindexpredictionsleague'

  get '/buyprediction/sports/:id' => 'prediction_games#buy', as: 'buypredictiongame'

  get '/:username/:type/new/sports/' => 'games#sportsgamesselect', as: 'sportsgamesselect'

  get '/:username/predictions/sports/:id' => 'prediction_games#show', as: 'predictiongamesshow'

  get 'prediction/sports/new/:id' => 'prediction_games#new', as: 'newpredictiongame'

  
  get '/:username/subscribers' => 'predictors#subscriberindex', as: 'predictorsubscriberindex'

  get ':league/posts/all/index' => 'pages#leaguearticleindex', as: 'leaguearticleindex'

  get 'sports/leagues/:league/predictions' => 'pages#leaguepredictionindex', as: 'leaguepredictionindex'

  get ':league/games' => 'pages#leaguegameindex', as: 'leaguegameindex'

  get 'sports/leagues/:league' => 'pages#leaguehome', as: 'leaguehome'

  get 'sports/leagues/:league/experts' => 'pages#league_predictors', as: 'leaguepredictors'

  get 'sports/leagues/:league/games' => 'pages#league_games', as: 'leaguegames'

  get 'editor' => 'sports#new'

  get '/posts/all/:type' => 'articles#index', as: 'articledashboard'

  get 'economics/:category' => 'prediction_economies#index', as: 'prediction_economies_index'

  get 'watchlist' =>'pages#mywatchlist'

  get 'sports-watchlist' => 'pages#sportswatchlist'
  get 'finance-watchlist' => 'pages#financewatchlist'
  get 'politics-watchlist' => 'pages#politicswatchlist'
  get 'misc-watchlist' => 'pages#miscwatchlist'

  get '/find-predictions/:prediction_type' => 'pages#findpredictions', as: 'findpredictions'

  get 'findsportspredictions' => 'prediction_games#findpredictiongames'

  get 'predictor_signin' => 'predictors#session#new'

  get 'myclosedpredictions' => 'prediction_games#index_closed'

  get 'predictiontype' => 'predictions#typeselect'

  get 'predictorpricing' => 'pages#predictorpricing'

  get 'sportsprediction' => 'predictions#newsportsprediction'

  get 'financeprediction' => 'predictions#newfinanceprediction'

  get 'miscprediction' => 'predictions#newmiscprediction'

  get 'admineditor' => 'admin#editor'

  get 'sportedit' => 'sports#index'

  get 'teamedit' => 'teams#index'

  get 'add_teams' => 'teams#new'

  get 'gamescore' => 'games#score'

  get 'sportpredictiontype' => 'pages#selectsportsprediction'

  get 'gameprediction' => 'prediction_games#index' #need

  get 'gameselect' => 'games#gameselect'

 

  get '/buyprediction/sports/:id' => 'prediction_games#show', as: 'showpredictiongame'

  post '/accounts/update' => 'accounts#update', as: 'accounts_update'
  

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new

    unless params[:predictor_id].nil?
      @predictor = Predictor.find(params[:predictor_id])
    end

    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    token = Stripe::Token.create(
    :card => {
    :number => params[:number],
    :exp_month => params[:exp-month],
    :exp_year => params[:exp-year],
    :cvc => params[:cvc]
              },
                )

    unless current_user.customer_id

      customer = Stripe::Customer.create(
                :description => "Customer for Futable",
                #:source => params[:stripeToken] # obtained with Stripe.js
                )

      current_user.update(:customer_id => customer.id)

    end

    customer = Stripe::Customer.retrieve(current_user.customer_id)

    customer.source = token

    customer.save

  # rescue Stripe::CardError => e
  #   flash[:error] = e.message
  #   redirect_to charges_path
  # end

    # if @predictor
    #   customer.subscriptions.create(:plan => @predictor.subscription_id)

    #   current_user.predictors << @predictor

    # end

  end

  def create

    @user = current_user

    unless params[:predictor_id].nil?
      @predictor = Predictor.find(params[:predictor_id])
    end

    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    token = Stripe::Token.create(
    :card => {
    :number => params[:number],
    :exp_month => params[:expmonth],
    :exp_year => params[:expyear],
    :cvc => params[:cvc]
              },
                )

    unless current_user.customer_id

      customer = Stripe::Customer.create(
                :description => "Customer for Futable",
                #:source => params[:stripeToken] # obtained with Stripe.js
                )

      current_user.update(:customer_id => customer.id)

    end

    customer = Stripe::Customer.retrieve(current_user.customer_id)


    begin

      customer.sources.create(:source => token.id)

    rescue Stripe::CardError => e
              flash[:error] = e.message
              redirect_to :back and return
        end

    customer.save

  # rescue Stripe::CardError => e
  #   flash[:error] = e.message
  #   redirect_to charges_path
  # end

    # if @predictor
        
    #     if Purchase.exists?(:user_id=> @user.id,:predictor_id=>@predictor.id)

    #       @purchase = Purchase.where(:user_id=> @user.id,:predictor_id=>@predictor.id)

    #       @purchase.each do |purchase|
    #         purchase.update(:premium => true)
    #       end

    #     else

    #       @purchase = Purchase.new

    #       @purchase.user_id = @user.id

    #       @purchase.predictor_id = @predictor.id

    #       @purchase.premium = true

    #       customer.subscriptions.create(:plan => @predictor.subscription_id)

    #       @purchase.save        

    #     end

    #   redirect_to root_path

    # else

      redirect_to payments_path

    # end

  end

  def index

    @action = "payment"

    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    if current_user.customer_id

      @customer = Stripe::Customer.retrieve(current_user.customer_id)

      if @customer.default_source

        @defaultcard = @customer.default_source

        @displaycard = @customer.sources.retrieve(@defaultcard)

        @list = @customer.sources.all(:limit => 5, :object => "card")

        @cards = @list.data

      end

    end

  end

  def make_default

    if params[:newdefault]

      Stripe.api_key = Rails.configuration.stripe[:secret_key]

      customer = Stripe::Customer.retrieve(current_user.customer_id)

      customer.default_source = params[:newdefault]

      customer.save

      if user_signed_in?

        current_user.update(:default_source => customer.default_source)
      end

    end

      redirect_to cardsindex_path(current_user.username)

  end

end

app/views/cards/_addcardform.html.erb
  	<%= form_tag cards_path, id: 'payment-form' do %>

  		<table class="card-form">

	      	<span class='payment-errors'></span>

	      	<tr class="add-card-form-header">
	      		<td class="add-card-header">
	      			<b>Add a Credit Card</b>
	      		</td>
	      	</tr>
	      	<tr>
	      		<td>
	      			Credit Card Number
	      		</td>
	      		<td>
	      			CVC
	      		</td>
	      	</tr>

	      	<tr>
	      		<td>
	      			<input name="number" class="card-number" pattern="[0-9]{13,16}"/>
	      		</td>
	      		<td>
	      			<input name="cvc" class="card-cvc"/>
	      		</td>
	      	</tr>

	      	<tr>
	      		<td colspan="2">
	      		Expiration
	      		</td>
	      	</tr>

	      	<tr>
	      		<td>
			      	<select name="expmonth" class="card-month"/>
			      		<option value selected="selected" disabled="disabled">month</option>
			      		<option value="01">01</option>
			      		<option value="02">02</option>
			      		<option value="03">03</option>
			      		<option value="04">04</option>
			      		<option value="05">05</option>
			      		<option value="06">06</option>
			      		<option value="07">07</option>
			      		<option value="08">08</option>
			      		<option value="09">09</option>
			      		<option value="10">10</option>
			      		<option value="11">11</option>
			      		<option value="12">12</option>
					</select>
				
			      	<select name="expyear" class="card-year"/>
			      		<option value selected="selected" disabled="disabled">Year</option>
			      		<option value="2015">2015</option>
			      		<option value="2016">2016</option>
			      		<option value="2017">2017</option>
			      		<option value="2018">2018</option>
			      		<option value="2019">2019</option>
			      		<option value="2020">2020</option>
			      		<option value="2021">2021</option>
			      		<option value="2022">2022</option>
			  		</select>
			  	</td>
			 </tr>

			 <tr>
	      		<td colspan="2">
	      		<input type="checkbox" name="defaultcard" value=true>Make Default</input>
	      		</td>
	      	</tr>

			 <tr>
	      		<td class="add-card-action">
	      			<button type="submit" class= "add-card-submit">Add Card</button>

	      		</td>

	      		<td class="add-card-action">
	      			<a id="addCardLink" class="cancel-card-submit" onclick="toggleModal();">cancel</a>
	      		</td>
	      	</tr>
		</table>

	<%end%>

app/views/cards/_addcardform_subscribe.html.erb
<div class="modal-container" id="divModal" style="display:none">

	<div class = "modal-form">

		<button class="close" onclick="toggleModal();">
		<span class="close-button">X</span>
	</button>

  	<%= form_tag cards_path(:predictor_id=>@predictor.id), id: 'payment-form' do %>

  		<table class="card-form">

	      	<span class='payment-errors'></span>

	      	<tr class="add-card-form-header">
	      		<td class="add-card-header">
	      			<b>Add a Credit Card</b>
	      		</td>
	      	</tr>
	      	<tr>
	      		<td>
	      			Credit Card Number
	      		</td>
	      		<td>
	      			CVC
	      		</td>
	      	</tr>

	      	<tr>
	      		<td>
	      			<input name="number" class="card-number" pattern="[0-9]{13,16}"/>
	      		</td>
	      		<td>
	      			<input name="cvc" class="card-cvc"/>
	      		</td>
	      	</tr>

	      	<tr>
	      		<td colspan="2">
	      		Expiration
	      		</td>
	      	</tr>

	      	<tr>
	      		<td>
			      	<select name="expmonth" class="card-month"/>
			      		<option value selected="selected" disabled="disabled">month</option>
			      		<option value="01">01</option>
			      		<option value="02">02</option>
			      		<option value="03">03</option>
			      		<option value="04">04</option>
			      		<option value="05">05</option>
			      		<option value="06">06</option>
			      		<option value="07">07</option>
			      		<option value="08">08</option>
			      		<option value="09">09</option>
			      		<option value="10">10</option>
			      		<option value="11">11</option>
			      		<option value="12">12</option>
					</select>
				
			      	<select name="expyear" class="card-year"/>
			      		<option value selected="selected" disabled="disabled">Year</option>
			      		<option value="2015">2015</option>
			      		<option value="2016">2016</option>
			      		<option value="2017">2017</option>
			      		<option value="2018">2018</option>
			      		<option value="2019">2019</option>
			      		<option value="2020">2020</option>
			      		<option value="2021">2021</option>
			      		<option value="2022">2022</option>
			  		</select>
			  	</td>
			 </tr>

			 <tr>
	      		<td colspan="2">
	      		<input type="checkbox" name="defaultcard" value=true>Make Default</input>
	      		</td>
	      	</tr>

			 <tr>
	      		<td class="add-card-action">
	      			<button type="submit" class= "add-card-submit">Add Card</button>

	      		</td>

	      		<td class="add-card-action">
	      			<a id="addCardLink" class="cancel-card-submit" onclick="toggleModal();">cancel</a>
	      		</td>
	      	</tr>
		</table>

	<%end%>
</div>
</div>

app/views/cards/_new_card_form.html.erb
<% @predictor = Predictor.find(@prediction_game.predictor_id)%>
<%= form_tag cards_path(:predictor_id => @predictor.id), id: 'chargeForm' do %>

    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= hidden_field_tag 'stripeToken' %>
    <%= hidden_field_tag 'stripeEmail' %>  

    <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Subscribe</button>
    <script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
    });
     document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: 'Onyx Predictions',
        description: 'Subscription to <%= @predictor.username.humanize.possessive %> name ($5/month)',
        amount: 499
    });
    e.preventDefault();
   })
  </script>
<% end %>

app/views/cards/_newcardform.html.erb
	<div class="card-form-container">

	  	<%= form_tag subscribe_new_card_path(:username=>@predictor.username), id: 'payment-form' do %>

	  		<% if flash[:error].present? %>
      			<div id="error_explanation">
        			<p><%= flash[:error] %></p>
      			</div>
    		<% end %>

	  		<table class="card-form">

		      	<span class='payment-errors'></span>

		      	<tr class="add-card-form-header">
		      		<td class="add-card-header">
		      			<b>Payment Method</b>
		      		</td>
		      	</tr>
		      	<tr>
		      		<td>
		      			Credit Card Number
		      		</td>
		      		<td>
		      			CVC
		      		</td>
		      	</tr>

		      	<tr>
		      		<td>
		      			<input name="number" class="card-number" pattern="[0-9]{13,16}"/>
		      		</td>
		      		<td>
		      			<input name="cvc" class="card-cvc"/>
		      		</td>
		      	</tr>

		      	<tr>
		      		<td colspan="2">
		      		Expiration
		      		</td>
		      	</tr>

		      	<tr>
		      		<td>
				      	<select name="expmonth" class="card-month"/>
				      		<option value selected="selected" disabled="disabled">month</option>
				      		<option value="01">01</option>
				      		<option value="02">02</option>
				      		<option value="03">03</option>
				      		<option value="04">04</option>
				      		<option value="05">05</option>
				      		<option value="06">06</option>
				      		<option value="07">07</option>
				      		<option value="08">08</option>
				      		<option value="09">09</option>
				      		<option value="10">10</option>
				      		<option value="11">11</option>
				      		<option value="12">12</option>
						</select>
					
				      	<select name="expyear" class="card-year"/>
				      		<option value selected="selected" disabled="disabled">Year</option>
				      		<option value="2015">2015</option>
				      		<option value="2016">2016</option>
				      		<option value="2017">2017</option>
				      		<option value="2018">2018</option>
				      		<option value="2019">2019</option>
				      		<option value="2020">2020</option>
				      		<option value="2021">2021</option>
				      		<option value="2022">2022</option>
				  		</select>
				  	</td>
				 </tr>

			</table>

			<button type="submit" class= "hero_cta">Confirm</button>

		<%end%>

	</div>

app/views/cards/create.html.erb
BBUBU

app/views/cards/index.html.erb
<script>
$(document).ready(function(){
    $("#addCardLink").click(function(){
        $(".add-card-container").toggle();
    });
});
</script>


<div class="confirm-wrap">

  <div class="confirm-container">
        
      <h1>Payment Information</h1>

        <% if @displaycard %>
				
				<b>Current Payment Method:</b> <br>
				<%=@displaycard.brand + " •••• •••• •••• " + @displaycard.last4 %> <br>
				Expiration Date:<br>
				<%= @displaycard.exp_month.to_s + "/" + @displaycard.exp_year.to_s %>

			<% end %>

			<%= current_user.default_source %>

			<br><br>
		      		
			<%if @cards %>

				<%= form_tag cards_default_path do %>

					<select name="newdefault"/>
			      		<option value selected="selected" disabled="disabled">update credit card</option>

				      	<% @cards.each do |card| %>

							<option value=<%=card.id%>><%=card.brand + " •••• •••• •••• " + card.last4 %>

						<%end%>

					</select>

					<br>

					<button type="submit" class= "signup-submit">Update</button>

				<%end%>

			<br>

			<% end %>

			<% if flash[:error].present? %>
      			<div id="error_explanation">
        			<p><%= flash[:error] %></p>
      			</div>
    		<% end %>

			<a id="addCardLink">Add a Credit Card</a>

			<Br><BR>

				<div class="add-card-container" style="display:none">
					<%=render 'cards/addcardform' %>
				</div>

  </div>

</div>