config/routes.rb
Rails.application.routes.draw do

  resources :messages

  resources :earnings_predictions

  resources :companies

  resources :price_items

  resources :topic_copies

  resources :topics

  resources :plans

  resources :prediction_economies

  resources :accounts

  resources :articles

  resources :cards

  resources :charges

  resources :bank_accounts

  resources :prediction_games

  resources :games

  resources :teams

  resources :sports

  resources :predictions

  resources :topics

  devise_for :users
  devise_for :admins
  devise_for :predictors

  root :to => 'pages#home'

  get "javatest" => "javascripts#dynamicgames.js"

  get 'home' => 'pages#home'

  get 'gamedash' => "games#index"

  get 'companies_quicksearch', :to => 'companies#quicksearch'

  get 'companies_index' => 'companies#index'

  get 'price_items' => "price_items#index"

  get 'top-posts' => 'pages#top_posts', as: 'top_posts'

  get '/me/bookmarks' => 'pages#bookmarks', as: 'bookmarks'

  get '/article/ajax_team/:team', :to => 'articles#ajax_team'

  get '/article/ajax_league/:game', :to => 'articles#ajax_league'

  get '/article/ajax_indicator/:typeId', :to => 'articles#ajax_indicator'

  get '/article/recommend/:article_id', :to => 'articles#ajax_recommend'

  get '/article/bookmark/:article_id', :to => 'articles#ajax_bookmark'

  get '/predictor/follow/:following_id', :to => 'predictors#ajax_following'

  get 'user_dashboard' => "pages#user_index"

  get "about" => "pages#about"

  get "login" => "devise/sessions#new"

  get 'dashboard' => 'pages#dashboard'

  get 'get_started' => 'pages#signup_dual_details'

  get 'all_categories' => 'pages#prediction_type_full_index'

  get 'predictoradminindex' => 'predictors#index'

  get 'select_category' => 'articles#select_category'

  get 'topic_copy_dashboard' => 'topic_copies#index'

  get 'posts' => 'articles#index'

  get 'experts' => 'predictors#predictorindex', as: 'predictorindex'

  get '/find-experts/:expert_type' => 'pages#findexperts', as: 'findexperts'

  get 'sportdashboard' => 'sports#index'

  post 'cards_default' => 'cards#make_default'

  post 'subscribe_new_card' => 'subscriptions#create'

  post 'update_predictor_price' => 'predictors#update_predictor_price'

  post 'bank_account_default' => 'bank_accounts#make_default'

  get '/:predictor/premium/confirm' => 'predictors#subscribe_confirm', as: 'subscribe_confirm'

  get 'subscribe' => 'subscriptions#create'

  get 'go_premium' => 'pages#premium_landing'

  get '/plan/:plan/confirm' => 'plans#confirm', as: 'plan_confirm'

  get 'plan/:plan/purchase' => 'plans#purchase', as: 'plan_purchase'

  get 'plans' => 'plans#index'

  get 'balance' => 'predictors#predictorbalance'

  get 'buy_prediction_game' => 'prediction_games#buy'

  get 'subscribe_to_predictor' => 'predictors#subscribe'

  get 'follow_predictor' => 'predictors#follow'

  get 'predictorpayeeedit' => 'accounts#edit'
  get 'bank_account_new' => 'bank_accounts#new'

  get '/users/edit/payments' => 'cards#index', as: 'payments'

  get '/tags/:tag' => 'pages#tag_show', as: 'tag_show'

  get '/topic/:topic' => 'pages#topic_show', as: 'topic_show_page'

  get '/topic/:topic/top' => 'pages#topic_top_articles', as: 'topic_top_articles'

  get '/topic/:topic/latest' => 'pages#topic_latest_articles', as: 'topic_latest_articles'

  get '/events/sports/:league' => 'games#findgames', as: 'find_prediction_games'

  get 'sports/leagues/:league/games/:id' => 'games#show', as: 'gameshow'

  get 'sports/leagues/:league/games/:id/predictions' => 'pages#gamepredictionindex', as: 'gamepredictionindex'

  get '/:league/games/:id/posts' => 'pages#gamearticleindex', as: 'gamearticleindex'

  get 'sports/leagues/:league/teams/:team' => 'teams#show', as: 'teamshow'

  get 'sports/leagues/:league/teams/:team/games' => 'teams#show_games', as: 'teamshowgames'

  get 'sports/leagues/:league/teams/:team/experts' => 'teams#expertindex', as: 'teamindexexperts'

  get '/:league/teams/:team/games' => 'teams#teamgameindex', as: 'teamgameindex'

  get 'sports/leagues/:league/teams' => 'sports#teamindex', as: 'sportsteamindex'

  get 'sports/leagues/:league/experts' => 'sports#expertindex', as: 'sportsexpertindex'

  get '/events/sports/:league/predictions/:game_id' => 'prediction_games#findpredictiongames', as: 'find_sports_predictions'
  
  get '/predictors/sports/:league' => 'predictors#findsportspredictors', as: 'find_sports_predictors'

  get '/:username/predictions' => 'predictors#predictionindex', as: 'predictorindexpredictions'

  get '/:username/rating' => 'predictors#rating', as: 'predictor_rating'

  get '/:username/predictions/:category' => 'predictors#predictionindex', as: 'predictorindexpredictionscategory'

  get '/:username/' => 'predictors#predictordashboard', as: 'predictordashboard'

  get '/:username/posts' => 'predictors#articleindex', as: 'predictorindexarticlessall'

  get '/posts/new/' => 'articles#new', as: 'new_post'

  get '/:username/posts/:id' => 'articles#show', as: 'predictorarticleshow'

  get '/:username/:category/leagues/:league' => 'predictors#predictionindex', as: 'predictorindexpredictionsleague'

  get '/buyprediction/sports/:id' => 'prediction_games#buy', as: 'buypredictiongame'

  get '/:username/:type/new/sports/' => 'games#sportsgamesselect', as: 'sportsgamesselect'

  get '/:username/predictions/sports/:id' => 'prediction_games#show', as: 'predictiongamesshow'

  get 'prediction/sports/new/:id' => 'prediction_games#new', as: 'newpredictiongame'

  
  get '/:username/subscribers' => 'predictors#subscriberindex', as: 'predictorsubscriberindex'

  get ':league/posts/all/index' => 'pages#leaguearticleindex', as: 'leaguearticleindex'

  get 'sports/leagues/:league/predictions' => 'pages#leaguepredictionindex', as: 'leaguepredictionindex'

  get ':league/games' => 'pages#leaguegameindex', as: 'leaguegameindex'

  get 'sports/leagues/:league' => 'pages#leaguehome', as: 'leaguehome'

  get 'sports/leagues/:league/experts' => 'pages#league_predictors', as: 'leaguepredictors'

  get 'sports/leagues/:league/games' => 'pages#league_games', as: 'leaguegames'

  get 'editor' => 'sports#new'

  get '/posts/all/:type' => 'articles#index', as: 'articledashboard'

  get 'economics/:category' => 'prediction_economies#index', as: 'prediction_economies_index'

  get 'watchlist' =>'pages#mywatchlist'

  get 'sports-watchlist' => 'pages#sportswatchlist'
  get 'finance-watchlist' => 'pages#financewatchlist'
  get 'politics-watchlist' => 'pages#politicswatchlist'
  get 'misc-watchlist' => 'pages#miscwatchlist'

  get '/find-predictions/:prediction_type' => 'pages#findpredictions', as: 'findpredictions'

  get 'findsportspredictions' => 'prediction_games#findpredictiongames'

  get 'predictor_signin' => 'predictors#session#new'

  get 'myclosedpredictions' => 'prediction_games#index_closed'

  get 'predictiontype' => 'predictions#typeselect'

  get 'predictorpricing' => 'pages#predictorpricing'

  get 'sportsprediction' => 'predictions#newsportsprediction'

  get 'financeprediction' => 'predictions#newfinanceprediction'

  get 'miscprediction' => 'predictions#newmiscprediction'

  get 'admineditor' => 'admin#editor'

  get 'sportedit' => 'sports#index'

  get 'teamedit' => 'teams#index'

  get 'add_teams' => 'teams#new'

  get 'gamescore' => 'games#score'

  get 'sportpredictiontype' => 'pages#selectsportsprediction'

  get 'gameprediction' => 'prediction_games#index' #need

  get 'gameselect' => 'games#gameselect'

 

  get '/buyprediction/sports/:id' => 'prediction_games#show', as: 'showpredictiongame'

  post '/accounts/update' => 'accounts#update', as: 'accounts_update'
  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  def confirm

    if user_signed_in?

      @plan = Plan.find(params[:plan])

      Stripe.api_key = Rails.configuration.stripe[:secret_key]

      if current_user.customer_id

        @customer = Stripe::Customer.retrieve(current_user.customer_id)

        if @customer.default_source

          @defaultcard = @customer.default_source

          @displaycard = @customer.sources.retrieve(@defaultcard)

          @list = @customer.sources.all(:limit => 5, :object => "card")

          @cards = @list.data

        end

      end

    elsif admin_signed_in? or predictor_signed_in?

        redirect_to root_path

    else

      redirect_to new_user_session_path
      
    end

  end

  def purchase

    if user_signed_in?

      @user = current_user

        Stripe.api_key = Rails.configuration.stripe[:secret_key]

        customer = Stripe::Customer.retrieve(@user.customer_id)

        @plan = Plan.find(params[:plan])

        customer.subscriptions.create(:plan => @plan.stripe_id)

    end

    redirect_to root_path

  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    if admin_signed_in?
      @plan = Plan.new
    end
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create

    if admin_signed_in?
      @plan = Plan.new(plan_params)

      Stripe.api_key = Rails.configuration.stripe[:secret_key]

      plan = Stripe::Plan.create(
            :amount => (@plan.cost * 100).to_i,
            :interval => 'month',
            :name => @plan.description,
            :currency => 'usd',
            :id => @plan.stripe_id
            )

      respond_to do |format|
        if @plan.save
          format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
          format.json { render :show, status: :created, location: @plan }
        else
          format.html { render :new }
          format.json { render json: @plan.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:stripe_id, :description, :cost, :credit_per_month)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stripe_id %><br>
    <%= f.text_field :stripe_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>

  <div class="field">
    <%= f.label :credit_per_month %><br>
    <%= f.text_field :credit_per_month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/confirm.html.erb
<script>
	$(document).ready(function(){

	    $("#currentPaymentLink").click(function(){

	    	$(".add-card-container").hide()
	    	

	    });

	    $("#addCardLink").click(function(){
	    	
	    	$(".add-card-container").show()
	    		

	    });

	});

</script>

<div class="content-panel-wrap">

	<div class="content-panel">

	  <div class="content-panel-container">
	    
	    <h1>Confirm Premium Upgrade</h1>

	    <h3 style="color:#11a657;"><%=number_to_currency(@plan.cost).to_s + "/month"%></h3>

	    <div class="large-table-container">

	    	<% if @displaycard %>

	    		<input type="radio" name="payment_type" value="current"  id="currentPaymentLink"  checked="checked"><b>Current Payment Method</b> (<%=@displaycard.brand + " ending in " + @displaycard.last4 %>)

				<br><br>

				<input type="radio" name="payment_type" value="add" id="addCardLink"><b>Add a Credit Card</b
				><br><br>

				<div class="add-card-container" style="display:none">
					<%=render 'cards/newcardform' %>
				</div>

			<% else %>
		      		
				<input type="radio" name="payment_type" value="add" id="addCardLink" checked="checked"><b>Add a Credit Card</b><br>

				<%=render 'cards/newcardform' %>

			<% end %>

	    </div>

	    <div style="text-align:center;">

	    	<%= link_to "Confirm", plan_purchase_path(@plan.id), {:class=>"subscribe_cta" }%>

	     </div>

	  </div>

	</div>

</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<h1>Listing plans</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Stripe</th>
      <th>Description</th>
      <th>Cost</th>
      <th>Credit/Month</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.id %></td>
        <td><%= plan.stripe_id %></td>
        <td><%= plan.description %></td>
        <td><%= plan.cost %></td>
        <td><%= plan.credit_per_month %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/purchase.html.erb
hola

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stripe:</strong>
  <%= @plan.stripe_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @plan.cost %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>